apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-app1
  namespace: app1
spec:
  project: default
  source:
    repoURL: https://github.com/smarty24/dev
    targetRevision: HEAD
    path: ./app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
syncPolicy:
  automated:
    prune: true
    selfHeal: true
