apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 namespace: default 
 name: app1
spec:
  project: default
  source:
    repoURL: https://github.com/smarty24/dev
    targetRevision: HEAD
    path: dev1/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
