apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache2
  name: apache2
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache2
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
