apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1-svc
    argocd.argoproj.io/instance: app1
  name: app1-svc
  namespace: app1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1-svc
status:
  loadBalancer: {}
