apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: app1
spec:
  project: default
  source:
    directory:
      include: 'dev1/app1/*'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
